### ISSUE TITLE
Misleading title in Manufacture List 2 and 3

### ISSUE THREAD

**Issue by skorpi0n** [alphp/WAN-IFRA-BarCode#1]
I bet it's just a copy-paste error, since Manufacture list 2 and 3 has same title as list 1
Shouldn't Manufacture List 2 have title:
>Manufacturers list 2 (Digit 13: 3 or 4)
And Manufacture List 3 have title:
>Manufacturers list 3 (Digit 13: 5 or 6)

**Comment by alphp** [comment]
Fixed it, thanks a lot.
